// src/lib/knowledgeBase.js
export const KB = {
  "Software Engineer": {
    icon:"💻",color:"#5b9cf6",field:"Technology",
    description:"Design, develop and maintain software applications. Work spans web, mobile, embedded systems and cloud infrastructure.",
    interests:["coding","building"],skills:["programming","logic","mathematics"],subjects:["cs","math_sub","physics"],
    grades:["excellent","good"],env:["office"],
    salary:{entry:"₹4–7 LPA",mid:"₹10–20 LPA",senior:"₹25–50 LPA+"},
    required_skills:["Programming","Data Structures","Algorithms","System Design"],
    learn:["Data Structures & Algorithms","System Design","Git & CI/CD","Cloud Basics"],
  },
  "Data Scientist": {
    icon:"📊",color:"#a78bfa",field:"Analytics / AI",
    description:"Extract insights from complex datasets using statistics and machine learning to drive data-driven decisions.",
    interests:["coding","data","science"],skills:["mathematics","statistics","programming","research"],subjects:["math_sub","cs","economics"],
    grades:["excellent","good"],env:["office","lab"],
    salary:{entry:"₹5–9 LPA",mid:"₹15–30 LPA",senior:"₹35–70 LPA+"},
    required_skills:["Python/R","Statistics","Machine Learning","SQL","Data Viz"],
    learn:["Python for Data Science","Statistics & Probability","ML Fundamentals","SQL"],
  },
  "AI / ML Engineer": {
    icon:"🤖",color:"#3ecfb0",field:"Artificial Intelligence",
    description:"Build and deploy machine learning models and intelligent systems — neural networks, NLP and computer vision.",
    interests:["coding","data","science","building"],skills:["programming","mathematics","statistics","logic"],subjects:["cs","math_sub","physics"],
    grades:["excellent"],env:["office","lab"],
    salary:{entry:"₹6–12 LPA",mid:"₹18–40 LPA",senior:"₹50–1Cr+"},
    required_skills:["Deep Learning","Python","Linear Algebra","Cloud ML"],
    learn:["Deep Learning (PyTorch/TF)","Linear Algebra & Calculus","Cloud ML (AWS/GCP)","MLOps"],
  },
  "Game Developer": {
    icon:"🎮",color:"#f06595",field:"Gaming / Interactive",
    description:"Create video games for PC, console, and mobile. Combines programming, art, and design to build interactive experiences.",
    interests:["coding","art","building"],skills:["programming","creativity","logic"],subjects:["cs","arts_sub","math_sub"],
    grades:["excellent","good","average"],env:["office"],
    salary:{entry:"₹3–6 LPA",mid:"₹8–20 LPA",senior:"₹22–50 LPA+"},
    required_skills:["Unity/Unreal","C#/C++","3D Math","Game Design"],
    learn:["Unity or Unreal Engine","C# or C++","Linear Algebra for Games","Game Design Patterns"],
  },
  "Cybersecurity Analyst": {
    icon:"🔐",color:"#5b9cf6",field:"Security / Tech",
    description:"Protect systems and networks from digital attacks. Roles span ethical hacking, SOC analysis, and security architecture.",
    interests:["coding","science","building"],skills:["programming","logic","research"],subjects:["cs","math_sub"],
    grades:["excellent","good"],env:["office","lab"],
    salary:{entry:"₹4–8 LPA",mid:"₹12–25 LPA",senior:"₹30–60 LPA+"},
    required_skills:["Networking","Linux","Penetration Testing","Cryptography"],
    learn:["Networking (TCP/IP)","Linux Administration","Ethical Hacking (CEH/OSCP)","SIEM Tools"],
  },
  "Doctor / Physician": {
    icon:"🩺",color:"#f06595",field:"Healthcare",
    description:"Diagnose and treat illness and health conditions — one of the most respected professions requiring years of dedicated training.",
    interests:["helping","science"],skills:["biology_skill","empathy","research"],subjects:["biology_sub","chemistry","psychology"],
    grades:["excellent","good"],env:["clinic"],
    salary:{entry:"₹6–12 LPA",mid:"₹15–40 LPA",senior:"₹40–1Cr+"},
    required_skills:["Clinical Knowledge","Diagnostics","Patient Communication","Biology/Chemistry"],
    learn:["NEET Preparation","Anatomy & Physiology","Clinical Skills","Medical Ethics"],
  },
  "Lawyer": {
    icon:"⚖️",color:"#f5c842",field:"Law & Justice",
    description:"Advise clients on legal rights, represent them in court and draft legal documents.",
    interests:["debating","writing","helping"],skills:["communication","writing_skill","research","logic"],subjects:["social","literature","economics"],
    grades:["excellent","good"],env:["office"],
    salary:{entry:"₹3–8 LPA",mid:"₹10–25 LPA",senior:"₹30–1Cr+"},
    required_skills:["Legal Research","Argumentation","Writing","Critical Thinking"],
    learn:["CLAT / Law Entrance","Constitutional Law","Legal Writing","Moot Court"],
  },
  "Graphic Designer / UI Designer": {
    icon:"🎨",color:"#f06595",field:"Creative / Design",
    description:"Create visual concepts to communicate ideas that inspire, inform and captivate across branding, digital products and media.",
    interests:["art","coding"],skills:["creativity","spatial","communication"],subjects:["arts_sub","cs","psychology"],
    grades:["excellent","good","average"],env:["office","clinic"],
    salary:{entry:"₹2.5–5 LPA",mid:"₹7–18 LPA",senior:"₹20–50 LPA+"},
    required_skills:["Adobe Suite","Typography","Color Theory","UX Principles"],
    learn:["Figma / Adobe XD","UI/UX Fundamentals","Typography & Color","Portfolio Building"],
  },
  "Psychologist / Counselor": {
    icon:"🧠",color:"#a78bfa",field:"Mental Health",
    description:"Study human behavior and help individuals manage mental health challenges and navigate life transitions.",
    interests:["helping","science","writing"],skills:["empathy","communication","research"],subjects:["psychology","biology_sub","social"],
    grades:["excellent","good","average"],env:["clinic","office"],
    salary:{entry:"₹3–6 LPA",mid:"₹8–18 LPA",senior:"₹20–40 LPA+"},
    required_skills:["Active Listening","Psychological Assessment","CBT Techniques","Research Methods"],
    learn:["Psychology (BSc/BA)","Counseling Techniques","Research Methods","Clinical Internships"],
  },
  "Architect": {
    icon:"🏗️",color:"#3ecfb0",field:"Design & Construction",
    description:"Design buildings and structures that are safe, functional, sustainable and aesthetically pleasing.",
    interests:["art","building","science"],skills:["creativity","spatial","mathematics"],subjects:["arts_sub","math_sub","physics"],
    grades:["excellent","good"],env:["office","field"],
    salary:{entry:"₹3–6 LPA",mid:"₹8–20 LPA",senior:"₹25–60 LPA+"},
    required_skills:["AutoCAD / Revit","Structural Knowledge","Design Principles","Project Management"],
    learn:["B.Arch Program","AutoCAD & Revit","Structural Engineering Basics","Sustainable Design"],
  },
  "Journalist / Content Creator": {
    icon:"📰",color:"#f5c842",field:"Media & Communications",
    description:"Investigate, report and communicate stories through print, broadcast and digital media.",
    interests:["writing","debating","teaching"],skills:["writing_skill","communication","research"],subjects:["literature","social","geography"],
    grades:["excellent","good","average","improving"],env:["field","office"],
    salary:{entry:"₹2.5–5 LPA",mid:"₹6–15 LPA",senior:"₹18–40 LPA+"},
    required_skills:["Writing & Editing","Investigative Research","Storytelling","Digital Tools"],
    learn:["Journalism (BA/Diploma)","Digital Media Tools","Investigative Journalism","SEO & Content Strategy"],
  },
  "Environmental Scientist": {
    icon:"🌿",color:"#63c654",field:"Environment & Science",
    description:"Study environmental problems and develop solutions spanning climate research, wildlife conservation and pollution control.",
    interests:["nature","science","writing"],skills:["research","biology_skill","statistics"],subjects:["geography","biology_sub","chemistry"],
    grades:["excellent","good","average"],env:["field","lab"],
    salary:{entry:"₹3–6 LPA",mid:"₹7–16 LPA",senior:"₹18–35 LPA+"},
    required_skills:["Field Research","Data Analysis","Environmental Laws","Biology/Chemistry"],
    learn:["BSc Environmental Science","GIS Mapping Tools","Climate Science","Policy & Regulation"],
  },
  "Teacher / Educator": {
    icon:"📚",color:"#5b9cf6",field:"Education",
    description:"Inspire and educate the next generation — teachers shape lives, minds and futures across every subject and level.",
    interests:["teaching","helping","writing"],skills:["communication","empathy","leadership"],subjects:["literature","social","psychology"],
    grades:["excellent","good","average","improving"],env:["office","clinic"],
    salary:{entry:"₹2.5–5 LPA",mid:"₹6–12 LPA",senior:"₹12–25 LPA+"},
    required_skills:["Curriculum Design","Communication","Patience","Subject Expertise"],
    learn:["B.Ed Degree","Subject Specialization","Educational Technology","Child Psychology"],
  },
  "Chartered Accountant / Finance": {
    icon:"💹",color:"#f5c842",field:"Finance & Accounting",
    description:"Manage financial records, audits, taxes and business strategy — CAs hold one of the most respected credentials in India.",
    interests:["business","science"],skills:["mathematics","logic","research"],subjects:["economics","math_sub"],
    grades:["excellent","good"],env:["office"],
    salary:{entry:"₹5–10 LPA",mid:"₹12–30 LPA",senior:"₹35–80 LPA+"},
    required_skills:["Accounting Standards","Taxation","Auditing","Financial Modeling"],
    learn:["CA Foundation / Intermediate","Tally & Excel","Corporate Finance","Taxation Law"],
  },
  "Mechanical Engineer": {
    icon:"⚙️",color:"#e0a800",field:"Engineering",
    description:"Design, analyse and manufacture mechanical systems — from engines and machines to robotics and HVAC systems.",
    interests:["building","science"],skills:["spatial","mathematics","logic"],subjects:["physics","math_sub","cs"],
    grades:["excellent","good"],env:["field","lab","office"],
    salary:{entry:"₹3–6 LPA",mid:"₹8–18 LPA",senior:"₹20–45 LPA+"},
    required_skills:["CAD (SolidWorks/AutoCAD)","Thermodynamics","Material Science","FEA Analysis"],
    learn:["B.Tech Mechanical","SolidWorks / CATIA","FEA with ANSYS","Robotics & Automation"],
  },
  "Entrepreneur": {
    icon:"🚀",color:"#f06595",field:"Business / Startups",
    description:"Build and scale your own company. Entrepreneurs identify problems and create solutions — combining vision, execution and resilience.",
    interests:["business","building","coding"],skills:["leadership","communication","creativity"],subjects:["economics","cs","psychology"],
    grades:["excellent","good","average","improving"],env:["office","field"],
    salary:{entry:"Variable",mid:"Variable",senior:"Unlimited potential"},
    required_skills:["Business Strategy","Product Thinking","Sales & Marketing","Financial Literacy"],
    learn:["Lean Startup Methodology","Business Model Canvas","Digital Marketing","Fundraising & VC"],
  },
  "Chef / Culinary Professional": {
    icon:"👨‍🍳",color:"#e0a800",field:"Hospitality / Food",
    description:"Master the art and science of cooking — chefs create experiences through food in restaurants, hotels, catering and media.",
    interests:["art","science","nature"],skills:["creativity","leadership","research"],subjects:["chemistry","arts_sub","biology_sub"],
    grades:["excellent","good","average","improving"],env:["clinic","field"],
    salary:{entry:"₹2–4 LPA",mid:"₹5–15 LPA",senior:"₹15–50 LPA+"},
    required_skills:["Culinary Techniques","Menu Design","Kitchen Management","Food Safety & HACCP"],
    learn:["Hotel Management / Culinary Arts","Classical Cooking Techniques","Pastry & Baking","Restaurant Business"],
  },

  // ── ELECTRONICS & SYSTEMS CAREERS ─────────────────────────────────────────

  "VLSI / Chip Design Engineer": {
    icon:"🔬",color:"#5b9cf6",field:"Semiconductor / VLSI",
    description:"Design digital and analog integrated circuits at the transistor level. Work spans RTL design, verification, physical design and tape-out — the backbone of every processor, phone and IoT device.",
    interests:["building","science","coding"],skills:["logic","mathematics","spatial"],subjects:["physics","cs","math_sub"],
    grades:["excellent","good"],env:["office","lab"],
    salary:{entry:"₹6–12 LPA",mid:"₹18–40 LPA",senior:"₹45–1Cr+"},
    required_skills:["Verilog / SystemVerilog","Digital Design","CMOS Circuit Design","Timing Analysis"],
    learn:["Digital Electronics & CMOS","Verilog & SystemVerilog","EDA Tools (Synopsys/Cadence)","Physical Design & STA"],
  },

  "Embedded Systems Engineer": {
    icon:"💾",color:"#3ecfb0",field:"Embedded / Firmware",
    description:"Write firmware and low-level software that runs directly on microcontrollers and processors. Found in everything from medical devices and automotive ECUs to smart appliances and industrial PLCs.",
    interests:["building","coding","science"],skills:["programming","logic","spatial"],subjects:["physics","cs","math_sub"],
    grades:["excellent","good"],env:["office","lab"],
    salary:{entry:"₹4–8 LPA",mid:"₹12–25 LPA",senior:"₹28–55 LPA+"},
    required_skills:["C / C++ (Bare Metal)","Microcontrollers (ARM/AVR/ESP32)","RTOS","Peripheral Protocols (UART/SPI/I2C)"],
    learn:["Embedded C & Bare Metal Programming","ARM Cortex-M Architecture","FreeRTOS / Zephyr","PCB Schematic Reading"],
  },

  "IoT Engineer": {
    icon:"🌐",color:"#a78bfa",field:"Internet of Things",
    description:"Connect physical devices to the internet — designing end-to-end systems spanning hardware sensors, firmware, communication protocols, cloud backends and dashboards.",
    interests:["building","coding","science","data"],skills:["programming","logic","research"],subjects:["physics","cs","math_sub"],
    grades:["excellent","good","average"],env:["office","lab","field"],
    salary:{entry:"₹4–8 LPA",mid:"₹10–22 LPA",senior:"₹25–50 LPA+"},
    required_skills:["Embedded C / MicroPython","MQTT / CoAP Protocols","Cloud Platforms (AWS IoT/Azure)","Sensor Integration"],
    learn:["ESP32 / Raspberry Pi Development","MQTT & IoT Protocols","AWS IoT Core or Azure IoT Hub","Edge Computing Basics"],
  },

  "Signal Processing Engineer": {
    icon:"📡",color:"#f06595",field:"Signal Processing / DSP",
    description:"Analyse, filter and transform signals — audio, video, radar, medical imaging, communications. DSP engineers work in 5G, SONAR, hearing aids, satellite systems and autonomous vehicles.",
    interests:["science","data","building"],skills:["mathematics","statistics","logic"],subjects:["physics","math_sub","cs"],
    grades:["excellent","good"],env:["office","lab"],
    salary:{entry:"₹5–10 LPA",mid:"₹14–30 LPA",senior:"₹32–65 LPA+"},
    required_skills:["MATLAB / Python (NumPy/SciPy)","DSP Theory (FFT, Filters)","Communication Systems","FPGA Implementation"],
    learn:["Signals & Systems (Oppenheim)","Digital Signal Processing","MATLAB & Simulink","FPGA Design with VHDL/Verilog"],
  },

  "Hardware / PCB Design Engineer": {
    icon:"🔧",color:"#e0a800",field:"Hardware Engineering",
    description:"Design and verify electronic circuit boards — from schematic capture and component selection to PCB layout, power integrity analysis and manufacturing handoff.",
    interests:["building","science"],skills:["spatial","mathematics","logic"],subjects:["physics","math_sub","cs"],
    grades:["excellent","good","average"],env:["office","lab"],
    salary:{entry:"₹3–7 LPA",mid:"₹10–20 LPA",senior:"₹22–45 LPA+"},
    required_skills:["Schematic Capture (KiCad/Altium)","PCB Layout & Signal Integrity","Power Electronics","EMI/EMC Standards"],
    learn:["KiCad or Altium Designer","Analog & Power Circuit Design","PCB Layout Best Practices","EMI/EMC Testing & Standards"],
  },

  "Control Systems / Robotics Engineer": {
    icon:"🤖",color:"#63c654",field:"Control Systems / Robotics",
    description:"Design feedback control systems and robotic mechanisms — from PID controllers in industrial machines to autonomous robot navigation and drone flight controllers.",
    interests:["building","science","coding"],skills:["mathematics","spatial","logic"],subjects:["physics","math_sub","cs"],
    grades:["excellent","good"],env:["office","lab","field"],
    salary:{entry:"₹4–9 LPA",mid:"₹12–28 LPA",senior:"₹30–60 LPA+"},
    required_skills:["Control Theory (PID/LQR)","ROS (Robot Operating System)","MATLAB / Simulink","Sensor Fusion"],
    learn:["Control Systems Theory","ROS2 & Robot Programming","MATLAB Simulink for Control","Computer Vision for Robotics"],
  },
};

export const CAREER_NAMES = Object.keys(KB);
